---
- name: check if elasticsearch is installed
  shell: 'dpkg-query -l elasticsearch | grep -e "ii\s*elasticsearch\s*{{elasticsearch.version}}"'
  register: is_elasticsearch_installed
  ignore_errors: True
  tags: elasticsearch

- name: dependencies for elasticsearch
  when: is_elasticsearch_installed|failed
  apt: pkg={{item}}
       state=present
  with_items:
  - openjdk-7-jre-headless
  become: yes
  tags: elasticsearch

- name: download elasticsearch
  when: is_elasticsearch_installed|failed
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{elasticsearch.version}}.deb
           dest=/tmp/elasticsearch-{{elasticsearch.version}}.deb
           force=no
  tags: elasticsearch

- name: install elasticsearch
  when: is_elasticsearch_installed|failed
  command: dpkg -i /tmp/elasticsearch-{{elasticsearch.version}}.deb
  become: yes
  tags: elasticsearch

- name: elasticsearch plugins
  shell: 'yes "Y" | ./bin/plugin install {{item.name}}
          chdir=/usr/share/elasticsearch/'
  with_items:
  - name: delete-by-query
  notify:
   - restart elasticsearch
  become: yes
  tags: elasticsearch

- name: elasticsearch service environment variables
  when: is_elasticsearch_installed|failed
  lineinfile: "dest=/etc/init.d/elasticsearch
              regexp='^export {{item.variable}}'
              insertafter='^export ES_JAVA_OPTS'
              line='export {{item.variable}}={{item.value}}'"
  with_items: "{{elasticsearch.environment}}"
  notify:
   - restart elasticsearch
  become: yes
  tags: elasticsearch

- name: ensure elasticsearch is running and enabled
  when: is_elasticsearch_installed|failed
  service: name=elasticsearch
           state=running
           enabled=yes
  become: yes
  tags: elasticsearch
